### ISSUE TITLE
Migrate to App::Cmd

### ISSUE THREAD

**Issue by rcaputo** [genehack/app-gitgot#34]
rt.cpan.org bug 91513 (currently still open) suggests that migration to App::Cmd is planned.  I would like that because the prerequisite MouseX::App::Cmd fails its tests for me.

**Comment by genehack** [comment]
Those failing tests should be fixed now.

I'm still planning on migrating off MouseX::App::Cmd, but I'm waiting for the release of Moo 2.0.
