### ISSUE TITLE
How to specify a default-command for tmux new-window?

### ISSUE THREAD

**Issue by gnustavo** [genehack/app-gitgot#41]
I liked the `got tmux` command. I already have a small shell script called `gitme` which prompts me with a menu of my repos and when I choose one it chdirs to it and invokes a subshell. However the subshell is invoked like this: `bash --rcfile ~/.bashrc.git`. Because normally I don't want my shell prompts to try to fetch git information when I'm not inside a git repo. Only when I'm inside a repo I setup bash to embelish its prompt with git information.

In order to do that with `got tmux` I guess it would have to invoke `tmux new-window` with a specific command instead of the default-command.

I couldn't come up with a good way to make it do so.

Would it be possible to set some global configuration in the `~/.gitgot` config file or is it only for repository information? I mean, there could be a configuration option that the tmux command could check to invoke tmux with the proper arguments...

Is there another way?

**Comment by genehack** [comment]
Sorry for letting this languish, I think I missed the original notification message from Github.

I have thought about adding a configuration section to the `.gitgot` file. That would require versioning the config file format (or doing something *really* ugly) and so I keep pushing it off. 

That said, there really isn't any "default command" -- all the tool is doing is `cd $repo->dir && system 'tmux new-window` -- so even if there was a place to put it in the config, I'm not sure what the invocation would look like.

**Comment by gnustavo** [comment]
The `tmux new-window` by default invokes your login shell. But you may supply it with another command to invoke as a single argument. For example `tmux new-window 'bash --rcfile /home/user/.bashrc.git'`.

**Comment by genehack** [comment]
@gnustavo - again, my apologies for the delay here. I've added a patch in d1ddc4b that adds an '-e' option to 'got mux'. Could you take a look and see if that does what you were looking for? My limited testing looks good but i worry about quoting and stuff like that.

@yanick - if you have a few minutes to look at this as well, I would appreciate it, as you wrote this code originally. 8^)

**Comment by yanick** [comment]
@genehack  Looks good. :+1: 

And if you want to see the config file grow and be somewhat versioned, create a ticket and ear-burn me. I shouldn't be able to resist the urge to play with it. ;-)

**Comment by genehack** [comment]
Thanks @yanick! @gnustavo -- any opinions? Would this work? 

(Oh, and @yanick, I think I am going to do the versioning config thing but I may selfishly hog it for myself, we'll see. ^.^)

**Comment by yanick** [comment]
@genehack ==b ^.^ d==

**Comment by gnustavo** [comment]
@genehack I'm sorry for the delay in responding to you.

It didn't work at first when I tried this:

```bash
got mux 1 -e "/bin/bash --rcfile $HOME/.bashrc.git"
```

The problem is the following line in mux.pm:

```perl
push( @args ,( sprintf "'%s'" , $self->opt->exec ))
```

It encloses the command in single-quotes. I changed it to this:

```perl
push( @args , $self->opt->exec )
```

And it worked.

It's weird because the following command works both ways:

```bash
got mux 1 -e bash
```

It seems to be a tmux thing, because the following commands work the same:

```bash
tmux new-window "bash"
tmux new-window "'bash'"
```

But of the next two only the first works:

```bash
tmux new-window "bash --rcfile $HOME/.bashrc.git"
tmux new-window "'bash --rcfile $HOME/.bashrc.git'"
```

So, I think you could simplify that push command. Unless you had some other reason (that I don't follow) to enclose the command in single-quotes.

Thank you!

**Comment by genehack** [comment]
I wasn't sure how the quoting was going to work out, honestly; the `sprintf` was a shot in the dark. 8^p 

I've removed that and I'm going to drop a dev release tonight. Assuming it does okay on CPAN Testers, I'll do a real release later next week. 

Thanks for yous help with this, @gnustavo (and you too @yanick)!
