### ISSUE TITLE
MouseX::App via mousex-getopt-0.35.tar.gz and Getopt::Long::Descriptive V 0.099

### ISSUE THREAD

**Issue by ronsavage** [genehack/app-gitgot#46]
It isn't possible to install App::GitGot V 1.22 with the above, which are pulled in automatically with cpanm. It seems the real problem is Getopt::Long::Descriptive.

**Comment by genehack** [comment]
What error are you getting with Getopt::Long::Descriptive?

**Comment by ronsavage** [comment]
See https://gist.github.com/ronsavage/c2cb241c488efa0a6f6f

**Comment by genehack** [comment]
So, those look like pretty harmless whitespace-driven test failures to me. I would say you have two not-mutually-exclusive options:

1) force-install MouseX::Getopt
2) file a bug against MouseX::Getopt

My short-term plans for GitGot involve migrating away from Mouse usage completely, for what it's worth. 

I'm going to close this ticket, as this is not a bug in GitGot. Thanks!
