### ISSUE TITLE
Failure with 'got fork <repo>' command, v 1.22

### ISSUE THREAD

**Issue by tbrowder** [genehack/app-gitgot#47]
Installed latest version, set up '$HOME/.github-identity' as directed, and got a failure when executing:

$  got fork https://github.com/perl6/doc.git
Reference bless( do{\(my $o = "")}, 'JSON::XS' ) did not pass type
constraint (not isa JSON::MaybeXS) (in $self->{"json"}) at (eval 280)
line 32
    "InstanceOf["JSON::MaybeXS"]" requires that the reference isa JSON::MaybeXS
    The reference (in $self->{"json"}) isa Exporter and JSON::XS

I got the same failure message when trying another repo.

**Comment by genehack** [comment]
This is actually a bug in Net::GitHub, which is what GitGot uses to talk to GitHub. I've reported that bug as https://github.com/fayland/perl-net-github/issues/61

**Comment by genehack** [comment]
As a workaround, you can also downgrade to Net::GitHub v0.72. If you use `cpanm`, that is as simple as:

    cpanm Net::GitHub@0.72

**Comment by tbrowder** [comment]
Thanks, John, that worked, but now I have another issue: "got fork -v <repo>" correctly forked repo to my gitgub account and then produced a local copy in my desired directory, but I saw no evidence of what was happening until the process quit and I saw my shiny new repo working directory.

**Comment by tbrowder** [comment]
'got fork --verbose <repo>' didn't show info either.

**Comment by genehack** [comment]
Yeah, it's UNIX-ish in that it doesn't make a whole lot of noise about what it's doing. What sort of output where you expecting?

**Comment by tbrowder** [comment]
On Mon, Mar 16, 2015 at 6:49 PM, John SJ Anderson
<notifications@github.com> wrote:
>
> Yeah, it's UNIX-ish in that it doesn't make a whole lot of noise about what it's doing. What sort of output where you expecting?

The usual info such as telling me it's creating a fork in my github
account, cloning it locally, etc.

It would also be useful for 'got fork' to go ahead and set up the
local repo with remotes to fetch from upstream and push to the user's
github account.

Other got commands could simplify the syncing necessary from upstream
to local and back to the user's github repo in preparation for the
user to make a pull request in his parent github repo.

Your 'got' is very neat and could be very useful, especially for those
of us trying to contribute to Per 6.

Best regards,

-Tom

**Comment by genehack** [comment]
I opened two new issues (#51, #52) for these two feature requests. Thanks for suggesting them. 8^)
