### ISSUE TITLE
test failures due to croak error message change in File::chdir

### ISSUE THREAD

**Issue by jscook** [genehack/app-gitgot#53]
Failed test 'expected error message' at t/lib/Test/App/GitGot/Repo/Git.pm line 24.

  'Failed to change directory to '/home/luser/proj/my-full-repo': No such file or directory at /Users/jsc/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2/Git/Wrapper.pm line 86.'

  doesn't match '(?^u:Can't locate directory)'  (in Test::App::GitGot::Repo::Git->test_current_branch)

Failed test 'expected error message' at t/lib/Test/App/GitGot/Repo/Git.pm line 33.

  'Failed to change directory to '/home/luser/proj/my-full-repo': No such file or directory at /Users/jsc/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2/Git/Wrapper.pm line 86. '

  doesn't match '(?^u:Can't locate directory)' (in Test::App::GitGot::Repo::Git->test_current_remote_branch)

  Testing with git version: 1.9.5 (Apple Git-50.3)

  Looks like you failed 2 tests of 32.

Sorry for the formatting issues.

This is because the wording of File::chdir changed.

https://metacpan.org/source/DAGOLDEN/File-chdir-0.1010/lib/File/chdir.pm

line 48.

If you'd like me to pull request fix this let me know.

**Comment by genehack** [comment]
Thanks for the bug report! I wasn't quite able to reproduce it myself, but I expanded the regex in the test case to be more accepting. 8^)

I put this out in a new trial release, if you'd like to grab that and see if fixed the problem for you.

**Comment by jscook** [comment]
Sure looks good to me:

--> Working on App::GitGot
Fetching http://cpan.metacpan.org/authors/id/G/GE/GENEHACK/App-GitGot-1.28-TRIAL.tar.gz ... OK
Configuring App-GitGot-1.28 ... OK
Building and testing App-GitGot-1.28 ... OK
Successfully installed App-GitGot-1.28 (upgraded from 1.27)
1 distribution installed

**Comment by genehack** [comment]
Thanks!
