### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by xsawyerx** [genehack/app-gitgot#57]
I don't understand GitGot enough right now to debug this. Sorry.

Both `09-update.t` and `12-fetch.t` fail.

Also, there are warnings coming from [Path::Tiny](https://metacpan.org/pod/Path::Tiny).

```
perl -Ilib t/09-update.t
Unrecognized option(s) passed to make_path(): err at /home/sawyer/perl5/lib/perl5/Path/Tiny.pm line 1051.
Unrecognized option(s) passed to make_path(): err at /home/sawyer/perl5/lib/perl5/Path/Tiny.pm line 1051.
not ok 1 - repo 1
#   Failed test 'repo 1'
#   at t/09-update.t line 21.
#                   'Unrecognized command: update.
#
# Usage:
# '
#     doesn't match '(?^u:1\)\s+bar\.git\s+\:\s+Updated)'
not ok 2 - repo 2
#   Failed test 'repo 2'
#   at t/09-update.t line 22.
#                   'Unrecognized command: update.
#
# Usage:
# '
#     doesn't match '(?^u:2\)\s+bargle\.git\s+\:\s+Checked out)'
not ok 3 - nothing on STDERR
#   Failed test 'nothing on STDERR'
#   at t/09-update.t line 23.
#          got: '  commands: list the application's commands
#       help: display a command's help screen
#
#
# '
#     expected: ''
not ok 4 - exit with 0
#   Failed test 'exit with 0'
#   at t/09-update.t line 24.
#          got: '1'
#     expected: '0'
1..4
# Looks like you failed 4 tests of 4.
```

**Comment by genehack** [comment]
Can you please give me: 

* Perl version
* Git version
* App::GitGot version you're testing
* version of Path::Tiny you have installed 

I can't reproduce this locally against HEAD in the repo using 5.23.5, Git 2.6.2, and Path::Tiny 0.076.

**Comment by xsawyerx** [comment]
Yes, sir!

Perl: 5.18.2
Git: 1.9.1
App::GitGot: Both CPAN and Github master.
Path::Tiny: 0.061

Which would you like me to update? Updating Git will be tricky though, but I have Perlbrew and can update Path::Tiny as well.

**Comment by genehack** [comment]
If I downgrade to Path::Tiny@0.061, I can reproduce at least some of the issues you're seeing, so I think upgrading Path::Tiny to current would be a good first step for you. 

(That Perl version should be fine, and I tested against Git v1.9.0 and that works fine too, so I think I just need to add a min version for Path::Tiny -- but confirmation from you on that would be appreciated.)

**Comment by xsawyerx** [comment]
Works! I would add a minimum version for `Path::Tiny`.

Thanks!
